name: control2
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - gradio==3.38.0
    - opencv-contrib-python==4.8.0.76
    - diffusers==0.20.0
    - transformers==4.31.0
    - einops==0.3.0
    - openai
    - git+https://github.com/huggingface/accelerate.git